name: Denná Analýza Tipov

on:
  schedule:
    - cron: '0 8 * * *' # Spustí sa každý deň o 08:00 UTC (9:00 nášho času)
  workflow_dispatch:      # Umožní spustiť skript manuálne tlačidlom

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3

      - name: Nastavenie Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Inštalácia knižníc
        run: pip install -r requirements.txt

      - name: Spustenie skriptu
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
        run: python main.py
