      - name: Run analysis script
        shell: bash
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
        run: |
          python main.py
